package cn.com.g12.pojo;

public class Course {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseid
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private String courseid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.coursename
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private String coursename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.period
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private Integer period;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.build
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private Boolean build;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseid
     *
     * @return the value of course.courseid
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public String getCourseid() {
        return courseid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseid
     *
     * @param courseid the value for course.courseid
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setCourseid(String courseid) {
        this.courseid = courseid == null ? null : courseid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.coursename
     *
     * @return the value of course.coursename
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public String getCoursename() {
        return coursename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.coursename
     *
     * @param coursename the value for course.coursename
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setCoursename(String coursename) {
        this.coursename = coursename == null ? null : coursename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.period
     *
     * @return the value of course.period
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public Integer getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.period
     *
     * @param period the value for course.period
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setPeriod(Integer period) {
        this.period = period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.build
     *
     * @return the value of course.build
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public Boolean getBuild() {
        return build;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.build
     *
     * @param build the value for course.build
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setBuild(Boolean build) {
        this.build = build;
    }
}