package cn.com.g12.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studid
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private String studid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studname
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private String studname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studsex
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private String studsex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studbirthday
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private Date studbirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stuclass
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private String stuclass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.studaddress
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private String studaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.postcode
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.ingrade
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private Float ingrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.burse
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    private BigDecimal burse;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studid
     *
     * @return the value of student.studid
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public String getStudid() {
        return studid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studid
     *
     * @param studid the value for student.studid
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setStudid(String studid) {
        this.studid = studid == null ? null : studid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studname
     *
     * @return the value of student.studname
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public String getStudname() {
        return studname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studname
     *
     * @param studname the value for student.studname
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setStudname(String studname) {
        this.studname = studname == null ? null : studname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studsex
     *
     * @return the value of student.studsex
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public String getStudsex() {
        return studsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studsex
     *
     * @param studsex the value for student.studsex
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setStudsex(String studsex) {
        this.studsex = studsex == null ? null : studsex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studbirthday
     *
     * @return the value of student.studbirthday
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public Date getStudbirthday() {
        return studbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studbirthday
     *
     * @param studbirthday the value for student.studbirthday
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setStudbirthday(Date studbirthday) {
        this.studbirthday = studbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stuclass
     *
     * @return the value of student.stuclass
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public String getStuclass() {
        return stuclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stuclass
     *
     * @param stuclass the value for student.stuclass
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setStuclass(String stuclass) {
        this.stuclass = stuclass == null ? null : stuclass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.studaddress
     *
     * @return the value of student.studaddress
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public String getStudaddress() {
        return studaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.studaddress
     *
     * @param studaddress the value for student.studaddress
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setStudaddress(String studaddress) {
        this.studaddress = studaddress == null ? null : studaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.postcode
     *
     * @return the value of student.postcode
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.postcode
     *
     * @param postcode the value for student.postcode
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.ingrade
     *
     * @return the value of student.ingrade
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public Float getIngrade() {
        return ingrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.ingrade
     *
     * @param ingrade the value for student.ingrade
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setIngrade(Float ingrade) {
        this.ingrade = ingrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.burse
     *
     * @return the value of student.burse
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public BigDecimal getBurse() {
        return burse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.burse
     *
     * @param burse the value for student.burse
     *
     * @mbggenerated Wed Apr 11 08:40:28 CST 2018
     */
    public void setBurse(BigDecimal burse) {
        this.burse = burse;
    }
}