package cn.com.g12.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import cn.com.g12.pojo.Grade;
import cn.com.g12.pojo.GradeCustom;
import cn.com.g12.pojo.GradeExample;

@Repository("gradeMapper")
public interface GradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue May 08 15:38:48 CST 2018
     */
    int countByExample(GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue May 08 15:38:48 CST 2018
     */
    int deleteByExample(GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue May 08 15:38:48 CST 2018
     */
    int deleteByPrimaryKey(Integer gno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue May 08 15:38:48 CST 2018
     */
    int insert(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue May 08 15:38:48 CST 2018
     */
    int insertSelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue May 08 15:38:48 CST 2018
     */
    List<Grade> selectByExample(GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue May 08 15:38:48 CST 2018
     */
    Grade selectByPrimaryKey(Integer gno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue May 08 15:38:48 CST 2018
     */
    int updateByExampleSelective(@Param("record") Grade record, @Param("example") GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue May 08 15:38:48 CST 2018
     */
    int updateByExample(@Param("record") Grade record, @Param("example") GradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue May 08 15:38:48 CST 2018
     */
    int updateByPrimaryKeySelective(Grade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table grade
     *
     * @mbggenerated Tue May 08 15:38:48 CST 2018
     */
    int updateByPrimaryKey(Grade record);
    
    public List<GradeCustom> selectAllGradeAndStuName() throws Exception;
    public void deleteGrades(int[] gnos)throws Exception;
    public List<GradeCustom> selectGradeByName(GradeCustom gradeCustom) throws Exception;
}